name: Build project

on: push
  
jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["release-v4.4", "release-v5.0"] 
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build project
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager idf-build-apps
          idf-build-apps find
          idf-build-apps build